import {
    Utensils,
    Stethoscope,
    ShoppingBag,
    Briefcase,
    Wrench,
    Car,
    GraduationCap,
    Landmark,
    Dumbbell,
    Music,
    Palette,
    Plane,
    Home,
    Wifi,
    Tv,
    Coffee,
    Pizza,
    Scissors,
    Shirt,
    Laptop,
    Folder,
    Building2,
    Store,
    Heart,
    Star,
    Camera,
    MapPin,
    Phone,
    Mail,
    Globe,
    Bus,
    Baby,
    Bed,
    TreePine,
    GlassWater,
    Cross,
    Shield,
    Smartphone,
    Umbrella,
    Sun,
    Moon,
    Clock,
    Calendar,
    Search,
    Bell,
    Gift,
    Tag,
    CreditCard,
    DollarSign,
    Zap,
    Map,
    Compass,
    Navigation,
    Truck,
    Ship,
    Train,
    CheckCircle,
    AlertTriangle,
    Info,
    HelpCircle,
    User,
    Users,
    Settings,
    Lock,
    Unlock,
    Key,
    Cloud,
    Wind,
    Activity,
    Hospital,
    Waves,
    Pill,
    ShoppingCart,
    KeyRound,
    Palmtree,
    Gamepad2,
    Printer,
    Award,
    Croissant,
    Hotel,
    School,
    Calculator,
    Cog,
    Film,
    Trophy,
    Scale,
    BookOpen,
    Building,
    Sofa,
    PartyPopper,
    IceCream,
    Candy,
    Sparkles,
    Cake,
    Bike,
    Gem,
    FlaskConical,
    Radiation,
    CarFront,
    Grid,
    LucideIcon
} from 'lucide-react'

// Map of icon names (lowercase) to Lucide components
const iconMap: Record<string, LucideIcon> = {
    Utensils,
    Stethoscope,
    ShoppingBag,
    Briefcase,
    Wrench,
    Car,
    GraduationCap,
    Landmark,
    Dumbbell,
    Music,
    Palette,
    Plane,
    Home,
    Wifi,
    Tv,
    Coffee,
    Pizza,
    Scissors,
    Shirt,
    Laptop,
    Folder,
    Building2,
    Store,
    Heart,
    Star,
    Camera,
    MapPin,
    Phone,
    Mail,
    Globe,
    Bus,
    Baby,
    Bed,
    TreePine,
    GlassWater,
    Cross,
    Shield,
    Smartphone,
    Umbrella,
    Sun,
    Moon,
    Clock,
    Calendar,
    Search,
    Bell,
    Gift,
    Tag,
    CreditCard,
    DollarSign,
    Zap,
    Map,
    Compass,
    Navigation,
    Truck,
    Ship,
    Train,
    CheckCircle,
    AlertTriangle,
    Info,
    HelpCircle,
    User,
    Users,
    Settings,
    Lock,
    Unlock,
    Key,
    Cloud,
    Wind,
    Activity,
    Hospital,
    Waves,
    Pill,
    ShoppingCart,
    KeyRound,
    Palmtree,
    Gamepad2,
    Printer,
    Award,
    Croissant,
    Hotel,
    School,
    Calculator,
    Cog,
    Film,
    Trophy,
    Scale,
    BookOpen,
    Building,
    Sofa,
    PartyPopper,
    IceCream,
    Candy,
    Sparkles,
    Cake,
    Bike,
    Gem,
    FlaskConical,
    Radiation,
    CarFront,
    Grid,
    // Lowercase fallbacks for robustness
    'utensils': Utensils,
    'cake': Cake,
    'bike': Bike,
    'gem': Gem,
    'flask-conical': FlaskConical,
    'flaskconical': FlaskConical,
    'radiation': Radiation,
    'car-front': CarFront,
    'carfront': CarFront,
    'landmark': Landmark,
    'stethoscope': Stethoscope,
    'shopping-bag': ShoppingBag,
    'briefcase': Briefcase,
    'wrench': Wrench,
    'car': Car,
    'graduation-cap': GraduationCap,
    'dumbbell': Dumbbell,
    'music': Music,
    'palette': Palette,
    'plane': Plane,
    'home': Home,
    'wifi': Wifi,
    'internet': Wifi,
    'tv': Tv,
    'coffee': Coffee,
    'cafe': Coffee,
    'pizza': Pizza,
    'fast-food': Pizza,
    'scissors': Scissors,
    'salon': Scissors,
    'barber': Scissors,
    'shirt': Shirt,
    'clothing': Shirt,
    'laptop': Laptop,
    'tech': Laptop,
    'building': Building,
    'store': Store,
    'heart': Heart,
    'star': Star,
    'camera': Camera,
    'mappin': MapPin,
    'phone': Phone,
    'mail': Mail,
    'globe': Globe,
    'bus': Bus,
    'baby': Baby,
    'bed': Bed,
    'treepine': TreePine,
    'glasswater': GlassWater,
    'cross': Cross,
    'shield': Shield,
    'smartphone': Smartphone,
    'umbrella': Umbrella,
    'sun': Sun,
    'moon': Moon,
    'clock': Clock,
    'calendar': Calendar,
    'search': Search,
    'bell': Bell,
    'gift': Gift,
    'tag': Tag,
    'credit-card': CreditCard,
    'dollar-sign': DollarSign,
    'zap': Zap,
    'map': Map,
    'compass': Compass,
    'navigation': Navigation,
    'truck': Truck,
    'ship': Ship,
    'train': Train,
    'check-circle': CheckCircle,
    'alert-triangle': AlertTriangle,
    'info': Info,
    'help-circle': HelpCircle,
    'user': User,
    'users': Users,
    'settings': Settings,
    'lock': Lock,
    'unlock': Unlock,
    'key': Key,
    'cloud': Cloud,
    'wind': Wind,
    'activity': Activity,
    'hospital': Hospital,
    'waves': Waves,
    'pill': Pill,
    'shopping-cart': ShoppingCart,
    'shoppingcart': ShoppingCart,
    'key-round': KeyRound,
    'keyround': KeyRound,
    'palm-tree': Palmtree,
    'palmtree': Palmtree,
    'gamepad-2': Gamepad2,
    'gamepad2': Gamepad2,
    'printer': Printer,
    'award': Award,
    'croissant': Croissant,
    'hotel': Hotel,
    'school': School,
    'calculator': Calculator,
    'cog': Cog,
    'film': Film,
    'trophy': Trophy,
    'scale': Scale,
    'book-open': BookOpen,
    'bookopen': BookOpen,
    'sofa': Sofa,
    'party-popper': PartyPopper,
    'partypopper': PartyPopper,
    'ice-cream': IceCream,
    'icecream': IceCream,
    'candy': Candy,
    'sparkles': Sparkles
}

interface CategoryIconProps {
    name?: string | null; // This is the 'icon' column value from DB
    size?: number;
    className?: string;
}

export function CategoryIcon({ name, size = 24, className }: CategoryIconProps) {
    if (!name) return <Folder size={size} className={className} />;

    // Support both exact case and lowercase matching for DB values
    const IconComponent = iconMap[name] || iconMap[name.toLowerCase().trim()] || Folder;

    return <IconComponent size={size} className={className} />;
}
